
from textblob.classifiers import NaiveBayesClassifier


train = [
( " my iphone 6 proximity sensor stopped working. any suggestions?  ", 'neu' ),
( " Debating if I should get this iphone6 or naaah!!!!  ", 'neu' ),
( " my iphone 6 proximity sensor stopped working. any suggestions?  ", 'neu' ),
( " RT @muktanpi: Watch UFC 184: Rousey vs. Zingano live stream online on your PC iphone ipad and mac #ufc184 TV Link", 'neu' ),
( " Finally got this iphone repaired", 'neu' ),
( " BestPrice #Deals_UK-100% Genuine Apple in USB Lightning Data Sync Charging Cable iphone  ", 'neu' ),
( " It's 2015 and my mom just learned that there's a front facing camera on her iphone  ", 'neu' ),
( " Anyone trying to cell an iphone  ", 'neu' ),
( " Selling an iphone 5 hmu if you're interested", 'neu' ),
( " Sale!!! Brown iphone wallet leather - Handmade Brown Leather iPhone Wallet  ", 'neu' ),
( " If anyone has a iphone5s case I can have then hmu  ", 'neu' ),
( " @scepticyrus Ahhh right And the newest iphone   ", 'neu' ),
( " Teaching my mom how to work with an iphone turned out to be more stressful than I thought......  ", 'neu' ),
( " I can't type in nepali letter in my iphone c6-01  ", 'neu' ),
( " My dad's having a difficult time with his iphone  ", 'neu' ),                                                 
( " Numberbook Download  Download numberbook for iphone and androd #IndvsSA8526  ", 'neu' ),
( " @rydelR5 @ratliffR5 iphone 6 ", 'neu' ),
( " Phones Offers &gt;&gt; http://t.co/cNLAvZmokH #034 For iphone 5s 5 bumper Color Clear TPU Silicone Frame Case W/ Metal ", 'neu' ),
( " @ItsJustDarc Yessss join the iphone crew  ", 'neu' ),
( " I just added this to my closet on Poshmark: iphone 5s Charging Case. http://t.co/8zKxBO0gCZ via @poshmarkapp #shopmycloset  ", 'neu' ),
( " 3D Handmade Bling Black BOW Big crystal pearl for iphone 5 5S HARD case cover  via eBay http://t.co/KUORs41CIk  ", 'neu' ),
( " @Diesel_Rezende which iphone and is it for verizon  ", 'neu' ),
( " anyone have an iphone 5 charger i can use):  ", 'neu' ),
( " @Justin_Le46 if only there was a iphone version  ", 'neu' ),
( " This is Why Slow Motion Was Invented (filmed on iphone 6) ", 'neu' ),
( " i think my iphone is broken :( it won't come on  ", 'neu' ),
( " HOT Handmade new Pink/Black diamonds Bling back case cover for iphone 5 / 5s!@  ", 'neu' ),
( " @thenickcolletti find my iphone app works good  ", 'neu' ),
( " New iphone case #newiphone  ", 'neu' ),
( " Where can i buy iphone 6 unlocked http://t.co/v8hqS4T4BJ #newiphone  ", 'neu' ),
( " Opened Graffiti request via iphone at 4069 Mission St. On i-280 northbound on electronic sign on overpass 1/2 way...  ", 'neu' ),
( " @sprintcare iphone 5  ", 'neu' ),
( " @ewdeslarga  um iphone  ", 'neu' ),
( " there was an 11 year old at mcdonalds today who had an iphone 5c and im sitting here with a butchered  ", 'neu' ),
( " iphone wallpaper success - Google'da Ara  ", 'neu' ),
( " somebody sell me there old iphone lol  ", 'neu' ),
( " @ForeverOneEli you happen to have an extra iphone 5 charger bro?  ", 'neu' ),
( " @smmywnchstr she also made me give her a cap sticker to put on her iphone case  ", 'neu' ),
( " After having a iphone all these years I finally got a custom ringtone  ", 'neu' ),
( " @SidneyDickhauss: good website to order cheap iphone 6 cases on 123 ", 'neu' ),
( " RT @Jake_Ryon: I'm about to buy the iphone 6 omg  ", 'neu' ),
( " Opened Report Concern Not Listed request via iphone at 71 PANATELLA RI NW http://t.co/CR8oKb48pw. Ice and water not draining. ice covers...  ", 'neu' ),
( " iphone bypass", 'neu' ),
( " Let your iphone help you to quit smoking http://t.co/JhTyhyncDz #NewYear #NewYearResolution #Wishes  ", 'neu' ),
( " @justeenftworld iphone  ", 'neu' ),
( " android vs iphone  ", 'neu' ),
( " Fee up to entrance fee straight a civilizedness iphone reference to processing solution: pjwD  ", 'neu' ),
( " 10000mAh Solar Powered Battery Panel f. MP3 Player PDA Charger Nokia iphone 4,5 &gt  ", 'neu' ),
( " Vend iphone 6  ", 'neu' ),
( " @jaaaccckieee they don't sell iphone5 anymore tho huh  ", 'neu' ),
( " Lots 5X USB Car Charger Adapter For iphone 4 S 5 C 5S 6 6 Plus Ipod Touch Nano - Full read by eBay: Price 4.26   ", 'neu' ),
( " @9GAGTweets wrong wrng Its ps4 and iphone 6 now  ", 'neu' ),
( " New iphone cover :)  ", 'neu' ),
( " someone sell me there old iphone plz  ", 'neu' ),
( " 3.5MM AUX MALE AUDIO EXTENSION CABLE CORD FOR GALAXY S5 NOTE 4 3 NEXUS 4 iphone6 - Full read by eBay: Price  ", 'neu' ),
( " @Kaash2x do u even have a iphone but HEY  ", 'neu' ),
( " iphone wallpaper success - Google'da Ara http://t.co/jn00faCzY2  ", 'neu' ),
( " but like what does a 7 year old do with an iphone  ", 'neu' ),
( " Opened report via iphone at Intersection Of Commonwealth Ave &amp; University Brg http://t.co/0udfoloa0i. Rampant intersection blocking. send...  ", 'neu' ),
( " My iphone photo gallery is filled with pictures of worksheets  ", 'neu' ),
( "iphone charges brake to easily", 'neg' ),
( "are you the iphone 5c cause you look cheap and plastic", 'neg' ),
( "I HATE iphone 6's", 'neg' ),
( " @Phallon: This iphone 6 is trashget you a note4 ", 'neg' ),
( " iphone 6+ is too big for my hand ", 'neg' ),
( " so in the 2 years i've had an iphone i've only broken 5 chargers, not bad  ", 'neg' ),
( " TheBetterDolan @Rachl1999Rl guitar!!! You'll get sick of the iphone an besides you have an iPad  ", 'neg' ),
( " RT @matthunter123: Just cracked my dumb iphone  ", 'neg' ),
( " @ageorge23 gmail en iphone sucks  ", 'neg' ),
( " RT @kara35637: iphone 5s batteries suck  ", 'neg' ),
( " the camera in iphone 6 protrudes out. dislike", 'neg' ),
( " iphone 6+ is like an elephant in my pocket	 ", 'neg' ),
( " I hate iphone chargers so much", 'neg' ),
( " night mode in iphone 5s sucks!", 'neg' ),
( " Why do iphone chargers last like 2 seconds?  ", 'neg' ),
( " In need of an iphone6 in my life", 'pos' ),
( " Kaaatfvsh : In need of an iphone6 in my life (via Twitter Photobooths are great for every  ", 'pos' ),
( " my iphone 6 looks so much preetier with out a case protector  ", 'pos' ),
( " we have a nexus problem-Elisabeth Kronk Warner on #indigenous peoples and #climatechange at #NDEL2015 #Yale  ", 'pos' ),
( " Miss you lyk ma iphone chager @CocoMeena: Lol.. Hi@abbercaty  ", 'pos' ),
( " Comforting yours fingers usage iphone keyboards: zStyqTOhd  ", 'pos' ),
( " Kinda want the 6plus now  ", 'pos' ),
( " buying an iphone 6 whatevers  ", 'pos' ),
( " @abbercaty: Miss you lyk ma iphone chager @CocoMeena: Lol.. ", 'pos' ),
( " Im getting an iphone 6 today and im hella exited!!!!  ", 'pos' ),
( " i need my iphone back   ", 'pos' ),
( " hey ya girl got an iphone today  ", 'pos' ),
( " I want an iphone 6  ", 'pos' ),
( " Just got the iphone 6 So happy!  ", 'pos' ),
( " I love iphone  ", 'pos' ),
( " RT @AllisonBurgrs: When ur mom buys a new iphone ", 'pos' ),
( " RT @meganwoodings_: need an iphone 6 in my life  ", 'pos' ),
( " shoutout to dad for purchasing me my 4th iphone 6 rn   ", 'pos' ),
( " Can someone bring me an iphone charger. How can someone loose something like that ?", 'pos' ),
( " I phone i phone i need a iphone  ", 'pos' ),
( " Earpods iphone 5/s/c original 100% clear sound great feeling :) guaranteed  ", 'pos' ),
( " I want an iphone again.  ", 'pos' ),
( " So excited to get my new black and blue iphone https  ", 'pos' ),
( " imagine if apple actually made iphone chargers that didn't break after a week  ", 'pos' ),
( " I love my blue and black iphone  ", 'pos' )
]

cl = NaiveBayesClassifier(train)


print cl.classify("charger ")

